name: Von Trapper
favicon: null
layout_spectrum: 0.814545693108812
typography_spectrum: 0.3982606583740562
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e7f2ef'
    - '#83674a'
    - '#14131a'
    - '#debbb4'
    - '#6b2721'
  brandStrength: 0.7508251692634076
  lightness: 0.46583007532171905
  saturation: 0.9467988947872072
  rhythmicContrast: 0.7987704793922603
purpose: []
